spring.application.name=ePermitMain
server.port =9090

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=epermit

jwt.secret=your_fixed_secret_key_here_jkenfjenfjefbjefbkejfbedefghij
jwt.expiry=60


file.signed.pdf.dir=C:/Users/Dhananjay/Downloads/ePermitMain (1)/ePermitMain/signed-pdf/
file.unsigned.pdf.dir=C:/Users/Dhananjay/Downloads/ePermitMain (1)/ePermitMain/unsigned-pdf/

file.formOne.pdf.dir=C:/Users/Dhananjay/Downloads/ePermitMain (1)/ePermitMain/formOne-pdf/

file.formThree.pdf.dir=C:/Users/Dhananjay/Downloads/ePermitMain (1)/ePermitMain/formThree-pdf/
file.formThreeA.pdf.dir=C:/Users/Dhananjay/Downloads/ePermitMain (1)/ePermitMain/formThreeA-pdf/
file.formThreeB.pdf.dir=C:/Users/Dhananjay/Downloads/ePermitMain (1)/ePermitMain/formThreeB-pdf/
file.formFive.pdf.dir=C:/Users/Dhananjay/Downloads/ePermitMain (1)/ePermitMain/formFive-pdf/
file.formSeven.pdf.dir=C:/Users/Dhananjay/Downloads/ePermitMain (1)/ePermitMain/formSeven-pdf/
file.formEight.pdf.dir=C:/Users/Dhananjay/Downloads/ePermitMain (1)/ePermitMain/formEight-pdf/


# set docs uploading path
#file.upload.temp-path=D:/nic_upload_docs
file.upload.temp-path=C:/Nic/nic_upload_docs


# Optional: Set file size limit
spring.servlet.multipart.max-file-size=200KB
spring.servlet.multipart.max-request-size=2MB

#spring.config.import=optional:file:/D:/applicationConfig.properties
#spring.config.import=C:/Nic/new_zip/applicationConfig.properties



